parameters:
  record.fields.currency_fields_type_map:
    default:
      currency:
        display: 'inline'
        showLabel:
        definition:
          '{currency}':
            logic:
              currency:
                key: 'update-currency'
                modes: ['edit', 'create', 'massupdate', 'filter']
                params:
                  fieldDependencies: ['{currency_id}']
                  currencyIdField: '{currency_id}'
                  baseCurrencyField: '{base_currency}'
                triggeringStatus: ['onAnyLogic']
          '{currency_id}':
            modes: ['edit', 'create', 'massupdate', 'filter']
            metadata:
              widthAuto: true
              widthFull: false
            type: 'enum'
            options: '__no_options__'
          '{base_currency}':
            display: 'none'
            logic:
              currency:
                key: 'update-base-currency'
                modes: ['edit', 'create', 'massupdate', 'filter']
                params:
                  fieldDependencies: ['{currency}']
                  currencyField: '{currency}'
                  currencyIdField: '{currency_id}'
                triggeringStatus: ['onAnyLogic']
