parameters:
  module.recordview.attachment_limits:
    row_compact_limit:
      XSmall: 1
      Small: 1
      Medium: 1
      Large: 2
      XLarge: 2
    row_default_limit:
      XSmall: 1
      Small: 1
      Medium: 1
      Large: 2
      XLarge: 2
    breakpoints_compact_limit:
      XSmall: 1
      Small: 1
      Medium: 1
      Large: 2
      XLarge: 2
    breakpoints_default_limit:
      XSmall: 1
      Small: 1
      Medium: 1
      Large: 2
      XLarge: 2
