App\MediaObjects\Entity\PublicDocumentMediaObject:
  file:
    mapping: public_documents_media_object # required
    filename_property: filePath  # required
    size: size
    mime_type: mimeType
    original_name: originalName
    dimensions: dimensions
